"""Original progressive tickets; checkpoints stay inside one platform level."""

TASKS = {'warehouse-route-planner': {'problem': 'The warehouse route preview draws over its endpoints, and '
                                        'a robot cannot plan a legal route through '
                                        'badge-controlled passages. Complete the existing route '
                                        'library and explain the search state.',
                             'levels': [{'kind': 'change',
                                         'title': 'Warehouse routes',
                                         'body': 'Grid rows are nonempty and rectangular. # is '
                                                 'blocked; S and E appear exactly once; . is open. '
                                                 'Lowercase a–d are reusable badges and uppercase '
                                                 'A–D are matching gates. Four moves cost one '
                                                 'each, with U,R,D,L ties. Collect a badge on '
                                                 'entering its tile. Optional forbidden edges are '
                                                 'directed coordinate pairs. shortest_route '
                                                 'returns a list of [row,column] including '
                                                 'endpoints or None. render_route marks only '
                                                 'internal open tiles with *, preserving S,E,walls '
                                                 'and badge/gate tiles. Invalid grids raise '
                                                 'ValueError before search. Never mutate input '
                                                 'rows. Working checkpoints: Repair '
                                                 'endpoint-preserving rendering. Implement '
                                                 'shortest legal routing, including unreachable '
                                                 'output. Support badge inventory and forbidden '
                                                 'directed edges; defend revisit behavior. Explain '
                                                 'the invariant and show a counterexample to a '
                                                 'plausible incorrect solution. Run pytest -q.'}]},
 'courier-payment-ledger': {'problem': 'Courier payouts truncate sub-hour work. Restore exact '
                                       'delivery accounting, then complete incremental payments '
                                       'and distinct-driver activity reporting.',
                            'levels': [{'kind': 'change',
                                        'title': 'Courier payments',
                                        'body': 'Rates are nonnegative integer cents/hour; '
                                                'start/end are integer seconds, end>start. Cost is '
                                                'rounded half-up once per delivery from '
                                                'rate*(end-start)/3600. Delivery ids are unique; '
                                                'exact duplicate records are idempotent, '
                                                'conflicting reuse raises ValueError without '
                                                'changing the ledger. Unknown drivers are '
                                                'rejected. pay_up_to(cutoff) returns newly paid '
                                                'cents for deliveries with end<=cutoff; repeated '
                                                'cutoffs pay nothing twice. total and unpaid are '
                                                'integer cents. peak counts distinct drivers in '
                                                '[window_start,window_end), with delivery '
                                                'intervals half-open; overlapping jobs by one '
                                                'driver count once. Working checkpoints: Correct '
                                                'second-level payout precision. Implement totals '
                                                'and cutoff payments without duplicate effects. '
                                                'Compute peak distinct-driver activity with '
                                                'touching intervals. Explain the invariant and '
                                                'show a counterexample to a plausible incorrect '
                                                'solution. Run pytest -q.'}]},
 'worker-job-dispatch': {'problem': 'A worker pool mishandles jobs arriving at a completion '
                                    'boundary and forgets queued work. Complete deterministic '
                                    'dispatch without changing FIFO arrival order.',
                         'levels': [{'kind': 'change',
                                     'title': 'Worker dispatch',
                                     'body': 'k is a positive integer; jobs are '
                                             '(id,arrival,duration), ids unique, arrival>=0 and '
                                             'duration>0 integers. Sort arrivals by time then '
                                             'original input index. Jobs queue FIFO when all '
                                             'workers are busy. Release all workers with '
                                             'finish<=dispatch time, then prefer the smallest '
                                             'available worker id. Outputs follow sorted arrival '
                                             'order and are [id,worker,start,finish]. Reject '
                                             'invalid input before scheduling and do not mutate '
                                             'the input list. Working checkpoints: Correct exact '
                                             'completion-boundary eligibility. Implement '
                                             'idle-worker and in-flight scheduling with queued '
                                             'jobs. Show deterministic ties and explain complexity '
                                             'using a slow small-input oracle. Explain the '
                                             'invariant and show a counterexample to a plausible '
                                             'incorrect solution. Run pytest -q.'}]},
 'bounded-recency-cache': {'problem': 'Recently read entries are evicted from a cache. Repair '
                                      'recency, then support resizing and atomic same-key '
                                      'creation.',
                           'levels': [{'kind': 'change',
                                       'title': 'Bounded cache',
                                       'body': 'Capacity is an integer>=0. get returns None for a '
                                               'miss and promotes a hit; put updates/promotes and '
                                               'evicts least recent entries until within capacity. '
                                               'Missing reads do not change recency. resize '
                                               'validates first and evicts oldest entries. '
                                               'get_or_put(key,factory) returns a cached value or '
                                               'computes/stores one; for positive capacity, '
                                               'concurrent successful callers for one missing key '
                                               'execute the factory once. Factory exceptions are '
                                               'not cached. Capacity zero stores nothing. Factory '
                                               'calls may be serialized across keys; explain that '
                                               'trade-off. No TTL in this contract. Working '
                                               'checkpoints: Repair read promotion and eviction. '
                                               'Implement resize, replacement and zero capacity. '
                                               'Make get_or_put atomic and preserve state when the '
                                               'factory fails. Explain the invariant and show a '
                                               'counterexample to a plausible incorrect solution. '
                                               'Run pytest -q.'}]},
 'service-impact-analysis': {'problem': 'A change detector confuses neighboring path prefixes and '
                                        'reports incomplete downstream impact. Repair path '
                                        'semantics and complete the impact graph.',
                             'levels': [{'kind': 'change',
                                         'title': 'Service impact',
                                         'body': 'Paths are absolute case-sensitive POSIX strings. '
                                                 'Collapse repeated slashes; remove trailing slash '
                                                 'except root. Reject . or .. segments. '
                                                 'ancestor(a,b) is true for equal paths or a '
                                                 'directory-boundary descendant; root contains all '
                                                 'paths. watched maps service ids to watched '
                                                 'paths. A file change affects watchers whose path '
                                                 'is an ancestor of the file; deleting a directory '
                                                 'also affects watched descendants. depends[A] '
                                                 'lists services A depends on; if B is affected '
                                                 'and A depends on B, A is affected. Return sorted '
                                                 'unique service ids. Validate unknown dependency '
                                                 'ids and all paths before computing; never mutate '
                                                 'input. Working checkpoints: Fix normalized path '
                                                 'boundaries and root behavior. Implement direct '
                                                 'file and deleted-directory impact. Propagate '
                                                 'through dependents with cycle termination. '
                                                 'Explain the invariant and show a counterexample '
                                                 'to a plausible incorrect solution. Run pytest '
                                                 '-q.'}]},
 'unique-word-selection': {'problem': 'A subset validator rejects legal smaller answers and '
                                      'accepts repeated characters. Repair legality, find an '
                                      'optimum, and explain scaling without overstating '
                                      'complexity.',
                           'levels': [{'kind': 'performance',
                                       'title': 'Unique word selection',
                                       'body': 'Words are lowercase a–z strings; empty strings are '
                                               'allowed. A selection contains distinct input '
                                               'indices in range; concatenated words must contain '
                                               'no repeated character, including within a word. A '
                                               'legal suboptimal selection is still legal. choose '
                                               'returns sorted indices maximizing total '
                                               'characters; ties prefer fewer selected words, then '
                                               'the lexicographically smallest index list. Empty '
                                               'input returns []. Repeated equal words remain '
                                               'separate occurrences. Nonalphabetic input raises '
                                               'ValueError. Input lists remain unchanged. Return '
                                               'an exact answer; no time-based greedy cutoff. '
                                               'Working checkpoints: Repair legality independently '
                                               'from optimality. Implement exact compatible-subset '
                                               'search with explicit ties. Compare small-input '
                                               'brute-force results and discuss larger-input '
                                               'pruning. Explain the invariant and show a '
                                               'counterexample to a plausible incorrect solution. '
                                               'Run pytest -q.'}]},
 'expression-cost-analysis': {'problem': 'A fixture loader truncates cost metadata, making a small '
                                         'expression analyzer look correct. Repair loading, '
                                         'implement cost/liveness analysis, then remove dead work '
                                         'and fold constants.',
                              'levels': [{'kind': 'performance',
                                          'title': 'Expression analysis',
                                          'body': 'load_case reads JSON with costs for +,-,*,/ as '
                                                  'nonnegative integers, totals=[time,memory], '
                                                  'and program as assignment strings; ignore '
                                                  'empty/comment-only lines. Programs assign each '
                                                  'variable once and include res. Each right-hand '
                                                  'side is one integer/name or one binary '
                                                  'operation on integers/names; unary minus on an '
                                                  'integer is allowed. Forward references to '
                                                  'assigned variables and duplicate assignments '
                                                  'are invalid; other names are inputs. '
                                                  'analyze(program,costs,optimize=False) returns '
                                                  '[time,peak_temporaries]. Arithmetic results '
                                                  'allocate a temporary before last-used operand '
                                                  'temporaries are freed; aliases share storage; '
                                                  'inputs/literals need none. Keep the output res '
                                                  'alive. With optimize=True, remove statements '
                                                  'not contributing to res and fold/propagate '
                                                  'constants. Integer division truncates toward '
                                                  'zero; constant division by zero raises '
                                                  'ValueError. Do not use eval or change the '
                                                  'stated allocation convention. Working '
                                                  'checkpoints: Repair multi-digit metadata '
                                                  'loading. Analyze arithmetic cost and '
                                                  'alias-aware temporary liveness. Eliminate dead '
                                                  'assignments and propagate/fold constants '
                                                  'without changing semantics. Explain the '
                                                  'invariant and show a counterexample to a '
                                                  'plausible incorrect solution. Run pytest -q.'}]},
 'room-reservation-scheduler': {'problem': 'A room service rejects back-to-back bookings and races '
                                           'two callers into one free slot. Repair interval '
                                           'semantics and implement atomic reservation.',
                                'levels': [{'kind': 'change',
                                            'title': 'Room reservations',
                                            'body': 'Bookings and requests are integer half-open '
                                                    'intervals [start,end) with end>start. overlap '
                                                    'is false at a touching endpoint. Scheduler '
                                                    'validates and stores a copy of input '
                                                    'bookings; existing overlaps are allowed and '
                                                    'searched as a occupied union. '
                                                    'find(duration,earliest,latest_end) returns '
                                                    '[start,end] for the earliest fully fitting '
                                                    'gap, or None; duration>0. reserve performs '
                                                    'find and insert as one atomic operation; '
                                                    'returned bookings are sorted. Failed '
                                                    'validation/reservation does not change stored '
                                                    'bookings. Locks may serialize callers for the '
                                                    'single room. Working checkpoints: Repair '
                                                    'overlap semantics. Find earliest gaps across '
                                                    'nested and unsorted bookings. Keep bookings '
                                                    'sorted and reserve atomically for concurrent '
                                                    'callers. Explain the invariant and show a '
                                                    'counterexample to a plausible incorrect '
                                                    'solution. Run pytest -q.'}]},
 'card-triple-strategy': {'problem': 'A strategy selects nonexistent or repeated physical cards. '
                                     'Repair move validation, implement a deterministic chooser '
                                     'and compare it with an exhaustive small-table oracle.',
                          'levels': [{'kind': 'change',
                                      'title': 'Card triples',
                                      'body': 'Cards are dictionaries {id,amount}; ids are unique '
                                              'strings, amount is an integer 1..9. A legal move '
                                              'contains exactly three distinct current ids summing '
                                              '15; equal amounts on different cards are allowed. '
                                              'legal returns False for a malformed move and '
                                              'validates the table first. choose returns the '
                                              'lexicographically smallest sorted legal id triple '
                                              'or None. remove returns a new table after a legal '
                                              'move, preserving order and input; illegal moves '
                                              'raise ValueError. Do not replace physical identity '
                                              'with value equality. Strategy-quality comparisons '
                                              'beyond correctness are discussion-only and require '
                                              'a separately stated scoring metric. Working '
                                              'checkpoints: Repair identity and multiplicity '
                                              'validation. Implement a deterministic legal chooser '
                                              'and safe removal. Compare with the exhaustive '
                                              'oracle; explain a changed scoring objective without '
                                              'silently changing legality. Explain the invariant '
                                              'and show a counterexample to a plausible incorrect '
                                              'solution. Run pytest -q.'}]},
 'structured-event-logger': {'problem': 'A configurable logger filters severity incorrectly and '
                                        'one failed sink prevents other destinations from '
                                        'receiving events. Complete predictable emission and '
                                        'atomic configuration.',
                             'levels': [{'kind': 'change',
                                         'title': 'Structured logger',
                                         'body': 'Levels are DEBUG<INFO<WARN<ERROR; emit includes '
                                                 'the threshold itself. Inject a clock and '
                                                 'callable sinks; emit(level,message,context=None) '
                                                 'returns a list of failed sink indices while '
                                                 'continuing to other sinks. Records contain '
                                                 'level,message,timestamp,context; deep-copy '
                                                 'context at emission and give each sink its own '
                                                 'deep copy. Unknown levels/configs raise '
                                                 'ValueError before changing config or writing '
                                                 'sinks. configure(level,sinks) affects future '
                                                 'calls. Suppressed events call neither the injected clock nor sinks. '
                                                 'JSON formatting must escape message '
                                                 'contents and preserve structured values. Sink '
                                                 'exceptions do not recursively log or get '
                                                 'silently represented as success. Working '
                                                 'checkpoints: Repair inclusive severity '
                                                 'filtering. Implement sink isolation and explicit '
                                                 'failure observations. Support atomic '
                                                 'reconfiguration and copied structured records. '
                                                 'Explain the invariant and show a counterexample '
                                                 'to a plausible incorrect solution. Run pytest '
                                                 '-q.'}]}}
