"""Candidate ticket briefs for the missing ranked top-twenty families."""

TASKS = {'extensible-hand-comparison': {'problem': 'Hand comparison: Work with the assistant in this '
                                           'existing Python codebase. Reproduce the incident, '
                                           'repair the contract and defend your verification.',
                                'levels': [{'kind': 'change',
                                            'title': 'Hand comparison',
                                            'body': 'Cards are strings with rank 2..10,J,Q,K,A and '
                                                    'suit C,D,H,S. parse_card returns '
                                                    '(numeric_rank,suit). A hand has exactly three '
                                                    'distinct physical cards; equal ranks in '
                                                    'different suits are permitted. Default '
                                                    'categories, weakest first, are distinct, '
                                                    'pair, triple. Keys are ranks descending for '
                                                    'distinct, (pair rank,kicker) for pair, and '
                                                    '(rank,) for triple. compare returns -1,0,1 '
                                                    'and never uses suits as a tie-break. An '
                                                    'optional order must be a permutation of those '
                                                    'three category names; it changes category '
                                                    'precedence only. No straights, flushes or '
                                                    'partial hands. Invalid cards, hands or orders '
                                                    'raise ValueError without mutating inputs. '
                                                    'Working checkpoints: Repair full-rank parsing '
                                                    'while preserving physical-card validation. '
                                                    'Implement category and tie-key comparison, '
                                                    'including exact ties. Verify supplied rule '
                                                    'variants and reject invented suit or poker '
                                                    'rules. Run pytest -q.'}]},
 'runway-event-scheduler': {'problem': 'Runway simulation: Work with the assistant in this '
                                       'existing Python codebase. Reproduce the incident, repair '
                                       'the contract and defend your verification.',
                            'levels': [{'kind': 'change',
                                        'title': 'Runway simulation',
                                        'body': 'schedule(flights,closures=(),cancellations=None) '
                                                'returns [id,start,end] occupancy records. Each '
                                                'flight is a dict with unique nonempty string id, '
                                                'nonnegative integer arrival, positive integer '
                                                'duration, kind landing or takeoff, and optional '
                                                'boolean emergency (default false). One runway, no '
                                                'preemption. At each free instant choose among '
                                                'arrived, not cancelled flights: emergency first '
                                                '(regardless of kind), then ordinary landing, then '
                                                'takeoff; ties by arrival then id. Cancellations '
                                                'map known ids to nonnegative integer instants and '
                                                'remove only flights not yet started when that '
                                                'instant is reached, including at dispatch. '
                                                'Closures are integer [start,end) with '
                                                '0<=start<end; no occupancy may overlap any '
                                                'closure. If the selected flight cannot fit, '
                                                'advance to the end of the obstructing closure and '
                                                're-evaluate arrivals and priorities. Finishing at '
                                                'closure start is legal. Reject invalid input and '
                                                'preserve all supplied collections. This is a toy '
                                                'simulation. Working checkpoints: Repair half-open '
                                                'occupancy boundaries. Implement non-preemptive '
                                                'scheduling with arrived-first eligibility and '
                                                'deterministic priority. Handle closures and '
                                                'waiting cancellations; reselect after delayed '
                                                'dispatch. Run pytest -q.'}]},
 'transactional-wallet-transfer': {'problem': 'Wallet transfers: Work with the assistant in this '
                                              'existing Python / FastAPI / SQLite codebase. '
                                              'Reproduce the incident, repair the contract and '
                                              'defend your verification.',
                                   'levels': [{'kind': 'change',
                                               'title': 'Wallet transfers',
                                               'body': 'Wallet(path,accounts=None) uses durable '
                                                       'SQLite accounts and successful receipts. '
                                                       'accounts seeds absent ids only; opening a '
                                                       'new Wallet on the same file preserves '
                                                       'committed balances and receipts. '
                                                       'transfer(id,source,destination,amount,fail_at=None) '
                                                       'returns '
                                                       '{id,source,destination,amount,balances:{source:new '
                                                       'balance,destination:new balance}}. '
                                                       'id/source/destination are nonempty '
                                                       'strings; amount is positive integer cents '
                                                       '(bool rejected), distinct existing '
                                                       'accounts. Invalid input raises '
                                                       'TransferError with status 400; unknown '
                                                       'account 404; insufficient funds 422; same '
                                                       'successful id with different payload 409. '
                                                       'Replay of same id and payload returns the '
                                                       'original stored result, even after later '
                                                       'transfers. Validation or failure changes '
                                                       'neither balances nor receipts; failed '
                                                       'requests are not reserved. '
                                                       "fail_at='after_debit' or 'after_receipt' "
                                                       'raises RuntimeError and rolls back all '
                                                       'effects. Balance check, both writes and '
                                                       'successful receipt are one transaction. '
                                                       'Independent Wallet instances/concurrent '
                                                       'debits cannot overdraw. balances() returns '
                                                       'all current balances. create_app(wallet) '
                                                       'exposes POST /transfers with JSON '
                                                       'id,source,destination,amount and maps '
                                                       'TransferError statuses; '
                                                       'successful/replayed responses are 200. '
                                                       'Test failure hooks are not an HTTP '
                                                       'parameter. Working checkpoints: Reproduce '
                                                       'a partial debit and repair rollback across '
                                                       'all effects. Verify durable payload-bound '
                                                       'retry receipts and immutable replay '
                                                       'results. Prove independent concurrent '
                                                       'connections cannot overdraw; verify the '
                                                       'HTTP boundary. Run pytest -q.'}]},
 'canvas-document-editor': {'problem': 'Canvas editor: Work with the assistant in this existing '
                                       'React / TypeScript codebase. Reproduce the incident, '
                                       'repair the contract and defend your verification.',
                            'levels': [{'kind': 'change',
                                        'title': 'Canvas editor',
                                        'body': 'Build and repair the supplied React shape editor. '
                                                'Document version 1 stores ordered shapes (unique '
                                                'nonempty id; rect or ellipse; finite x,y; '
                                                'positive finite width,height; nonempty color) and '
                                                'selected id or null. Insertion selects the new '
                                                'shape. Pointer movement affects only the selected '
                                                'shape; divide screen deltas by positive zoom to '
                                                'obtain document deltas. A completed drag creates '
                                                'one undo record regardless of pointer move count; '
                                                'releasing outside the surface completes it. Color '
                                                'and deletion affect only selection; deletion '
                                                'clears selection. Undo/redo preserve exact '
                                                'document state; a new committed action clears '
                                                'redo. Save/load JSON preserves ids, coordinates, '
                                                'dimensions, colors, order and selection. Validate '
                                                'before replacing state; malformed documents and '
                                                'duplicate ids preserve the previous state. The '
                                                'React UI must render these operations and an '
                                                'invalid-load error. SVG is the supplied editable '
                                                'surface; adding a different rendering library is '
                                                'unnecessary. Working checkpoints: Repair '
                                                'screen-to-document coordinate conversion and '
                                                'verify selected-shape isolation. Implement '
                                                'validated document loading, preserving the '
                                                'current design on rejection. Verify '
                                                'completed-drag history and rendered save/reload; '
                                                'explain snapshot costs. Run npm test.'}]},
 'movie-search-routing': {'problem': 'Search and routes: Work with the assistant in this existing '
                                     'React / Express / TypeScript codebase. Reproduce the '
                                     'incident, repair the contract and defend your verification.',
                          'levels': [{'kind': 'change',
                                      'title': 'Search and routes',
                                      'body': 'Repair the supplied movie app and Express API. '
                                              'Case-insensitive title substring, exact genre and '
                                              'minimum-year filters combine with AND, before '
                                              'stable id-ascending sort and pagination of size '
                                              'two; return rows and total matching count. URL '
                                              'query is canonical UI state. Decode q exactly once '
                                              'via URLSearchParams; encode through the inverse '
                                              'serializer. Missing q/genre means empty, missing '
                                              'minYear means null, missing page means one; page '
                                              'must be a safe positive integer written as decimal '
                                              'digits without leading zero, minYear four digits '
                                              '1000..9999. Invalid query returns HTTP 400. Filter '
                                              'changes reset page to one; refresh and popstate '
                                              'hydrate inputs and results from URL. GET '
                                              '/api/movies/:id returns the movie or 404. Direct '
                                              '/movies/:id and /movies serve the HTML app shell; '
                                              'React shows the loaded detail or Not found. Show '
                                              'loading/error state; an older request must not '
                                              'replace results for a later URL. Inputs/dataset '
                                              'stay unchanged. Unknown genres are allowed and '
                                              'match nothing. Working checkpoints: Repair combined '
                                              'HTTP predicates before sorting and pagination. Make '
                                              'URL-driven rendered state survive refresh/back and '
                                              'reject stale responses. Verify direct '
                                              'browser/detail/404 routes and literal query round '
                                              'trips. Run npm test.'}]}}
