// Self-contained decorative background: <promptcode-background>.
class PromptCodeBackground extends HTMLElement {
  connectedCallback(){
    if(this.shadowRoot)return;
    const root=this.attachShadow({mode:'open'});
    const snippets=["# promptcode / robustness.py\n# illustrative evaluation fixture\n\n@stress_test(seed=42)\ndef invoice_noise(sample):\n    variants = mutate(sample,\n        whitespace=True,\n        missing_fields=True,\n        mixed_currency=True)\n\n    for variant in variants:\n        output = candidate(variant)\n        assert schema.accepts(output)\n        record(output, variant)\n\nsuite.run(repeats=3)\nmanifest.freeze()\n", "// promptcode / trace.stream\n// illustrative execution events\n\n\u2192 challenge.loaded     invoice_v3\n\u2192 sandbox.ready        isolated\n\u2192 candidate.started    workflow.ts\n\u2502\n\u251c\u2500 model.call          trace.begin()\n\u251c\u2500 schema.validate     fields.check()\n\u251c\u2500 retry.inspect       budget.check()\n\u2514\u2500 evidence.capture    trace.close()\n\nconst report = await compare({\n  candidate: runs.current,\n  baseline: runs.naive,\n  metrics: [quality, cost, stability]\n});\n\nawait evidence.persist(report);\n", "{\n  \"fixture\": \"adversarial-input\",\n  \"version\": \"promptcode/eval-v3\",\n  \"input\": {\n    \"document\": \"invoice_scan.txt\",\n    \"attack\": \"instruction_override\"\n  },\n  \"expected\": {\n    \"schema\": \"Invoice\",\n    \"ignore_untrusted_commands\": true,\n    \"cite_source_fields\": true\n  },\n  \"checks\": [\n    \"grounded_output\",\n    \"budget_compliance\",\n    \"repeatable_result\"\n  ]\n}\n", "-- promptcode / evidence.sql\n-- inspect the work behind the score\n\nSELECT\n  candidate_id,\n  COUNT(*) AS evaluated_runs,\n  AVG(schema_valid) AS quality,\n  SUM(cost_usd) AS total_cost,\n  MAX(retry_count) AS peak_retries\nFROM workflow_evidence\nWHERE challenge = 'invoice_v3'\nGROUP BY candidate_id;\n\n+ add hidden input variants\n+ compare against naive baseline\n+ attach reproducible run manifest\n- infer ability from one answer\n\nreview(evidence);\nhuman.make_hiring_decision();\n"];
    const escape=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
    root.innerHTML=`<style>:host{display:block;position:absolute;inset:0;overflow:hidden;pointer-events:none;user-select:none}.columns{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:30px;height:100%;opacity:.19;transform:rotate(-7deg) scale(1.15)}.stream{width:max-content;min-width:100%;animation:flow 36s linear infinite;animation-play-state:paused}.stream:nth-child(even){animation-direction:reverse;animation-duration:44s}.stream:nth-child(3){animation-duration:50s}pre{font:12px/2.3 'DM Mono',ui-monospace,monospace;color:#8f9d7b;margin:0;padding:0 10px;white-space:pre}pre span{color:#c4f542}pre small{display:block;font:10px/3 ui-monospace,monospace;letter-spacing:2px;color:#c4f542;border-bottom:1px solid #c4f54235;margin-bottom:12px}:host([running]) .stream{animation-play-state:running}@keyframes flow{to{transform:translateY(-50%)}}@media(max-width:650px){.columns{grid-template-columns:repeat(2,minmax(0,1fr));gap:15px}.stream:nth-child(n+3){display:none}pre{font-size:10px}}@media(prefers-reduced-motion:reduce){.stream{animation:none!important}}</style><div class="columns">${snippets.map((s,i)=>{const block=`<pre><small>${['01 / STRESS SUITE','02 / EXECUTION TRACE','03 / HIDDEN FIXTURE','04 / EVIDENCE QUERY'][i]}</small>${escape(s).replace(/\b(def|return|const|await|for|class|async|export|with|assert|SELECT|FROM|WHERE|GROUP|BY|AS)\b/g,'<span>$1</span>')}</pre>`;return `<div class="stream">${block.repeat(4)}</div>`;}).join('')}</div>`;
    this.setAttribute('aria-hidden','true');
    this.observer=new IntersectionObserver(entries=>entries.forEach(entry=>this.toggleAttribute('running',entry.isIntersecting&&!this.paused)));
    this.observer.observe(this);
  }
  disconnectedCallback(){this.observer?.disconnect();}
}
if(!customElements.get('promptcode-background'))customElements.define('promptcode-background',PromptCodeBackground);
document.querySelectorAll('.hero-motion').forEach(button=>button.addEventListener('click',()=>{
  const background=button.closest('.hero-layout').querySelector('promptcode-background');
  background.paused=!background.paused;background.toggleAttribute('running',!background.paused);
  button.textContent=background.paused?'Play background':'Pause background';button.setAttribute('aria-pressed',String(background.paused));
}));
